"""Rich CLI summary renderer (PRD §10).

Prints an analyst-friendly terminal summary of a :class:`~phishbowl.report.view.ReportView`:
a colour-coded verdict banner, the top scoring reasons, authentication results,
IOC tables, routing, and attachments.

Two safety notes drive the implementation:

* Every email-derived string is wrapped in a Rich :class:`~rich.text.Text` with
  markup disabled, so a Subject like ``[bold]`` or a body full of brackets is
  shown literally and can never inject Rich console markup. The view layer has
  already stripped terminal control characters and defanged indicators.
* ``highlight=False`` on the console keeps Rich from re-styling (and thus
  fragmenting) those literal strings.
"""

from __future__ import annotations

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from .view import ReportView

# Severity slug → Rich colour for the verdict banner and score.
_SEVERITY_STYLE = {
    "benign": "green",
    "low": "green3",
    "elevated": "yellow",
    "high": "dark_orange",
    "critical": "bright_red",
}

_AUTH_STYLE = {
    "pass": "green",  # nosec B105 - Rich colour name for an auth result, not a credential
    "fail": "bright_red",
    "softfail": "yellow",
    "temperror": "yellow",
    "permerror": "yellow",
    "neutral": "dim",
    "none": "dim",
}

# Connector outcome → Rich colour for the enrichment panel.
_OUTCOME_STYLE = {
    "used": "green",
    "skipped": "dim",
    "failed": "yellow",
}

# Keep the CLI summary tight — the HTML/JSON carry the full picture.
_MAX_REASONS = 8
_MAX_IOCS_PER_TYPE = 12


def _t(value: str | None, style: str = "") -> Text:
    """A markup-free Text cell (email-derived strings never become Rich markup)."""
    return Text(value or "—", style=style)


def render_cli(view: ReportView, console: Console | None = None) -> None:
    """Print the rich CLI summary for ``view`` to ``console`` (or a fresh one)."""
    console = console or Console(highlight=False)
    style = _SEVERITY_STYLE.get(view.severity, "white")

    _verdict_banner(view, console, style)
    if view.redaction.enabled:
        cats = f" ({', '.join(view.redaction.categories)})" if view.redaction.categories else ""
        console.print(
            Text(
                f"PII redaction active{cats} — recipients/internal topology withheld.",
                style="italic dim",
            )
        )
    if view.embedded_email_count > 0:
        n = view.embedded_email_count
        console.print(
            Text(
                f"Note: {n} attached email(s) detected — this verdict is for the outer "
                f"wrapper. Re-run with --inner to triage the enclosed message.",
                style="italic yellow",
            )
        )
    console.print()
    _reasons(view, console)
    _enrichment(view, console)
    _auth(view, console)
    _iocs(view, console)
    _routing(view, console)
    _attachments(view, console)
    console.print(
        Text(
            "defensive-only · never sends, detonates, fetches, or remediates · "
            f"generated by {view.tool}",
            style="dim",
        )
    )


def _verdict_banner(view: ReportView, console: Console, style: str) -> None:
    body = Text()
    body.append(f"{view.score}", style=f"bold {style}")
    body.append(f" / {view.max_score}  ", style="dim")
    body.append(view.verdict, style=f"bold {style}")
    if view.subject:
        body.append("\nSubject: ", style="dim")
        body.append(view.subject)  # plain append: never parsed as Rich markup
    body.append(
        f"\n{len(view.fired_rules)} rule(s) fired · {view.ioc_total} indicator(s) · "
        f"offline score {view.offline_score}",
        style="dim",
    )
    title = Text("PHISHBOWL VERDICT", style=f"bold {style}")
    subtitle = _t(view.source.filename, "dim")
    console.print(Panel(body, title=title, subtitle=subtitle, border_style=style, padding=(1, 2)))


def _reasons(view: ReportView, console: Console) -> None:
    if not view.fired_rules:
        console.print(Text("No scoring rules fired — no strong indicators.\n", style="dim"))
        return
    table = Table(title="Why this score", title_style="bold", title_justify="left", expand=True)
    table.add_column("Reason", ratio=3)
    table.add_column("Evidence", ratio=4)
    table.add_column("Wt", justify="right", style="bold")
    table.add_column("Src", style="dim")
    shown = view.fired_rules[:_MAX_REASONS]
    for rule in shown:
        table.add_row(
            _t(rule.description),
            _t("; ".join(rule.evidence)),
            Text(f"+{rule.weight:g}"),
            _t(rule.source),
        )
    console.print(table)
    extra = len(view.fired_rules) - len(shown)
    if extra > 0:
        console.print(Text(f"… and {extra} more reason(s) in the full report.", style="dim"))
    console.print()


def _enrichment(view: ReportView, console: Console) -> None:
    enrichment = view.enrichment
    if not enrichment.enabled:
        return
    table = Table(
        title="Enrichment (OSINT connectors)",
        title_style="bold",
        title_justify="left",
        expand=True,
    )
    table.add_column("Connector", style="cyan", no_wrap=True)
    table.add_column("Status", no_wrap=True)
    table.add_column("Detail", ratio=3)
    for conn in enrichment.connectors:
        table.add_row(
            _t(conn.connector),
            Text(conn.outcome, style=_OUTCOME_STYLE.get(conn.outcome, "white")),
            _t(conn.note),
        )
    console.print(table)
    console.print(
        Text(
            "Enrichment augments the offline verdict — it never gates it. "
            "Points it added are tagged [enrichment] above.",
            style="dim",
        )
    )
    console.print()


def _auth(view: ReportView, console: Console) -> None:
    line = Text("Auth   ")
    for i, a in enumerate(view.auth):
        if i:
            line.append("   ")
        line.append(f"{a.mechanism}=", style="dim")
        line.append(a.result, style=_AUTH_STYLE.get(a.result, "white"))
    console.print(line)
    console.print()


def _iocs(view: ReportView, console: Console) -> None:
    if not view.ioc_groups:
        console.print(Text("No indicators extracted.\n", style="dim"))
        return
    table = Table(title="Indicators (defanged)", title_style="bold", title_justify="left")
    table.expand = True
    table.add_column("Type", style="cyan", no_wrap=True)
    table.add_column("Indicator", ratio=3)
    table.add_column("Seen in", style="dim", ratio=2)
    for group in view.ioc_groups:
        for ioc in group.items[:_MAX_IOCS_PER_TYPE]:
            note = ""
            if ioc.wrapper:
                note = f"  [wrapper: {ioc.wrapper}{', unresolved' if ioc.unresolved else ''}]"
            table.add_row(
                _t(ioc.type),
                _t(ioc.value_display + note),
                _t(", ".join(ioc.provenance)),
            )
        hidden = len(group.items) - min(len(group.items), _MAX_IOCS_PER_TYPE)
        if hidden > 0:
            table.add_row(_t(group.type, "dim"), Text(f"… +{hidden} more", style="dim"), _t(""))
    console.print(table)
    console.print()


def _routing(view: ReportView, console: Console) -> None:
    if not view.routing and not view.sending_ip_display:
        return
    line = Text(f"Routing  {len(view.routing)} hop(s)", style="bold")
    console.print(line)
    if view.sending_ip_display:
        sip = Text("  Sending IP: ", style="dim")
        sip.append(view.sending_ip_display, style="cyan bold")
        console.print(sip)
    for hop in view.routing:
        seg = Text(f"  {hop.index}. ", style="dim")
        if hop.from_:
            seg.append("from ")
            seg.append(hop.from_, style="cyan")
        if hop.by:
            seg.append(" by ")
            seg.append(hop.by, style="cyan")
        console.print(seg)
    console.print()


def _attachments(view: ReportView, console: Console) -> None:
    if not view.attachments:
        return
    table = Table(title="Attachments", title_style="bold", title_justify="left", expand=True)
    table.add_column("Filename")
    table.add_column("Type (declared/detected)", style="dim")
    table.add_column("Size", justify="right")
    table.add_column("Flags", style="bright_red")
    for att in view.attachments:
        types = f"{att.declared_type or '—'} / {att.detected_type or '—'}"
        table.add_row(
            _t(att.filename),
            _t(types),
            _t(att.size_human),
            _t(", ".join(att.flags)),
        )
    console.print(table)
    console.print()
